# fly.toml app configuration file generated for new-weather-x-1718951688-client on 2024-06-21T06:35:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'new-weather-x-1718951688-client'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
